FROM spark:4.0.1-python3

RUN curl -L -o /opt/spark/jars/hadoop-aws-3.4.1.jar \
        https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.4.1/hadoop-aws-3.4.1.jar && \
    curl -L -o /opt/spark/jars/bundle-2.24.6.jar \
        https://repo1.maven.org/maven2/software/amazon/awssdk/bundle/2.24.6/bundle-2.24.6.jar && \
    curl -L -o /opt/spark/jars/postgresql-42.7.9.jar \
        https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.9/postgresql-42.7.9.jar
