FROM apache/airflow:3.1.7rc1-python3.13
RUN mkdir -p /opt/airflow/dependencies
WORKDIR /opt/airflow/dependencies
COPY --chown=airflow:airflow ./dependencies/sql.txt  ./sql.txt 
RUN pip install -r ./sql.txt --no-cache-dir
COPY --chown=airflow:airflow ./dependencies/table-frameworks.txt ./table-frameworks.txt
RUN pip install -r ./table-frameworks.txt --no-cache-dir
COPY --chown=airflow:airflow ./dependencies/simple-libs.txt  ./simple-libs.txt 
RUN pip install -r ./simple-libs.txt --no-cache-dir
ENTRYPOINT ["airflow", "standalone"]