{
 "title": "web_logs",
 "time": { "from": "2025-11-06T17:16:21.945Z", "to": "2025-12-22T08:39:20.022Z" },
 "panels": [
  {
   "title": "error_count",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date, error_count\r\nFROM error_counts_mv\r\nwhere status_code_group = 4 \r\nORDER BY date DESC;"
    },
    {
     "rawSql": "SELECT date, error_count\r\nFROM error_counts_mv\r\nwhere status_code_group = 5\r\nORDER BY date DESC;"
    }
   ]
  },
  {
   "title": "response_time_ms",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT url, avg(response_time) AS avg_response_ms\r\nFROM web_logs wl \r\nGROUP BY url\r\norder by avg(response_time) desc\r\nlimit 20"
    }
   ]
  },
  {
   "title": "top 10 users by requests",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT user_id, count(url) as request_count\r\nFROM web_logs wl \r\nGROUP BY user_id \r\nORDER BY count(url) DESC\r\nLIMIT 10"
    }
   ]
  }
 ]
}